### ISSUE TITLE
Filebot not found because its in a Docker container

### ISSUE THREAD

**Issue by vakrolme** [Laharah/deluge-FileBotTool#36]
Hi, thanks for the plugin.

I am getting "Filebot not found", and the plugin turns off in the preferences on each system restart.

I am running my setup on an armhf NAS, so to avoid dealing with compilation, I run Deluge as a container and Filebot as another container. The `filebot` command in the Deluge container is aliased to run `filebot` in the Filebot container (by binding with host machine's Docker process). So running `filebot -version` from inside the Deluge container gives a few seconds lag, but other than that there's no difference from running it natively (AFAIK). Now, I'm not sure how `find_executable` works, so I tried to dupe the plugin by appending PATH with a fake path, gave more privileges to deluged — still, my limited knowledge of Linux is insufficient to solve this.

Is it possible to make this setup work?

Here's my deluge image:
```
FROM lsioarmhf/deluge
RUN apk update
RUN apk add docker
RUN apk update
RUN apk add openrc --no-cache
RUN rc-update add docker boot
RUN echo 'alias filebot="docker exec filebot filebot"' >> ~/.bashrc

CMD export PATH=$PATH:$ADDITIONAL_PATH; /bin/echo -e "ADDITIONAL_PATH is $ADDITIONAL_PATH\nPATH is $PATH"

RUN chown root:root /usr/bin/deluge
RUN chmod 4755 /usr/bin/deluge
```

Docker-compose:
```
version: '2'
services:
  filebot:
    image: filebot
    command: tail -F anything
    volumes:
      - /share/Kevin:/Kevin
  deluge:
    image: deluged:latest
    privileged: true
    command: tail -F anything
    volumes:
      - f966a27a1b07c155350094f94e986c07faef0746c3638455a63165f22ffad30f:/config
      - 6ddcd2b08cfa8025b0a2b3ed1dc9fd51dd44f26afa9caf66b0a5ee69080d0c29:/downloads
      - /share/Kevin:/Kevin
      - "/var/run/docker.sock:/var/run/docker.sock"
    #environment:
      #- ADDITIONAL_PATH=/usr/bin/filebot
    ports:
      - "1791:1791"
      - "1792:1792"
      - "1776:58846"
      - "58946:58946"
      - "8112:8112"
```
